name: 'build-and-test' 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to be your CI task/script
          runCmd: bash ./helper.sh config && bash ./helper.sh build && bash ./helper.sh test
